mijn_bestand= open("page1.md", "w")
mijn_bestand.write("#title")
mijn_bestand.write("\n")
mijn_bestand.write("hello")
mijn_bestand.close()    

mijn_bestand= open("page2", "w")
mijn_bestand.write("# YMAL")
mijn_bestand.write("\n")
mijn_bestand.write("---")
mijn_bestand.write("\n")
mijn_bestand.write("voornaam: Dario")
mijn_bestand.write("\n")
mijn_bestand.write("achternaam: Gilles")
mijn_bestand.write("\n")
mijn_bestand.write("leeftijd: 18")
mijn_bestand.write("\n")
mijn_bestand.write("---")
mijn_bestand.close()